### ISSUE TITLE
JB系列试用指南

### ISSUE THREAD

**Issue by Ideaye** [pengzhile/ja-netfilter#12]
ja-netfilter
https://www.wolai.com/xavier/8RXodWT5GbmT4ZRutyzUzA?theme=dark

**Comment by unixc3t** [comment]
这个即使用了ja-netfilter也需要第一次使用注册一下？

**Comment by Ideaye** [comment]
> 这个即使用了ja-netfilter也需要第一次使用注册一下？

Jetbrains限制，必须要登录才能试用

**Comment by unixc3t** [comment]
@Ideaye  谢谢

**Comment by pengzhile** [comment]
针对任何产品的issue请不要发在这里，谢谢。
