### ISSUE TITLE
测试smartsvn 14.1.1 无效

### ISSUE THREAD

**Issue by zhoujin7** [pengzhile/ja-netfilter#14]
测试smartsvn 14.1.1 无效

测试步骤:
编辑
C:\Users\admin\AppData\Roaming\SmartSVN\smartsvn.vmoptions
内容:
`-javaagent:C:/Users/admin/ja-netfilter/ja-netfilter.jar=C:/Users/admin/ja-netfilter/janf_config.txt -Djanf.debug=1`
```

janf_config.txt内容:
```
[URL]
PREFIX,https://store.smartgit.com/check
```

PS C:\Users\admin> smartsvn

  ============================================================================

    ja-netfilter-v1.1.3

    A javaagent lib for network filter :)

    https://github.com/pengzhile/ja-netfilter

  ============================================================================
```
启动后, 选择试用, 然后关闭smartsvn
修改系统时间改到2022年12月1日
再次启动smartsvn, 提示证书过期

**Comment by pengzhile** [comment]
针对任何产品的issue请不要发在这里，谢谢。
