### ISSUE TITLE
2021.3.1版本的DataGrip无法使用

### ISSUE THREAD

**Issue by dploop** [pengzhile/ja-netfilter#15]
全家桶其他都行，不过都是2021.3.1以下的，DataGrip现在不行

**Comment by huangcaijj** [comment]
2.3还用这个干啥

**Comment by demonDH** [comment]
> 全家桶其他都行，不过都是2.3以下的，DataGrip现在不行

我idea2021.3直接打不开了咋回事

**Comment by 89632a16** [comment]
> > 全家桶其他都行，不过都是2.3以下的，DataGrip现在不行
> 
> 我idea2021.3直接打不开了咋回事

有可能 ja-netfilter 文件路径错了吧。

**Comment by demonDH** [comment]
是安装完idea然后直接修改idea.vmoptions文件，末尾加上-javaagent:/实际路径/ja-netfilter.jar就行了吧

**Comment by demonDH** [comment]
> 

是安装idea然后直接修改idea.vmoptions文件，导出完成-javaagent:/实际路径/ja-netfilter.jar就行了吧
能实现什么效果，打开idea不会提示注册？

**Comment by demonDH** [comment]
> > > 全家桶其他都行，不过都是2.3以下的，DataGrip现在不行
> > 
> > 
> > 我idea2021.3直接打不开了咋回事
> 
> 有可能 ja-netfilter 文件路径错了吧。

是安装idea然后直接修改idea.vmoptions文件，然后再末尾添加-javaagent:/实际路径/ja-netfilter.jar就行了吧
能实现什么效果，打开idea不会提示注册？

**Comment by ZeroMessiah** [comment]
> > > > 全家桶其他都行，不过都是2.3以下的，DataGrip现在不行
> > > 
> > > 
> > > 我idea2021.3直接打不开了咋回事
> > 
> > 
> > 有可能 ja-netfilter 文件路径错了吧。
> 
> 是安装idea然后直接修改idea.vmoptions文件，然后再末尾添加-javaagent:/实际路径/ja-netfilter.jar就行了吧 能实现什么效果，打开idea不会提示注册？

这只是个正经的防火墙插件，功能要靠你自己想象

**Comment by demonDH** [comment]
> > > > > 全家桶其他都行，不过都是2.3以下的，DataGrip现在不行
> > > > 
> > > > 
> > > > 我idea2021.3直接打不开了咋回事
> > > 
> > > 
> > > 有可能 ja-netfilter 文件路径错了吧。
> > 
> > 
> > 是安装idea然后直接修改idea.vmoptions文件，然后再末尾添加-javaagent:/实际路径/ja-netfilter.jar就行了吧 能实现什么效果，打开idea不会提示注册？
> 
> 这只是个正经的防火墙插件，功能要靠你自己想象

emmm,janf_config.txt也配了的

**Comment by dploop** [comment]
> 2021.3.1

是 2021.3.1 这个版本，说错了

**Comment by Ideaye** [comment]
[ja-netfilter简易使用指南](https://www.wolai.com/xavier/8RXodWT5GbmT4ZRutyzUzA?theme=dark)

**Comment by Ideaye** [comment]
> > 全家桶其他都行，不过都是2.3以下的，DataGrip现在不行
> 
> 我idea2021.3直接打不开了咋回事

打不开说明javaagent路径配置错了
