### ISSUE TITLE
PluginManager-getAllPluginClasses这里，为什么要用currentDirectory下面的plugins文件夹下的ja-netfilter.jar?

### ISSUE THREAD

**Issue by wmszhe** [pengzhile/ja-netfilter#16]
看了下代码，比如我的路径是 /a/b/ja-netfilter.jar

那么currentDirectory应该是 /a/b/

getAllPluginClasses这里，直接 currentDirectory.listFiles((d, n) -> n.endsWith(".jar")) 就能取到 ja-netfilter.jar 吧

为何还要从 plugins 下面找 ja-netfilter.jar

这样岂不是需要放2个ja-netfilter.jar

/a/b/ja-netfilter.jar
/a/b/pulgins/ja-netfilter.jar

**Comment by pengzhile** [comment]
没有要到plugins下找ja-netfilter.jar，是在找它的插件

**Comment by wmszhe** [comment]
额，理解错了😅
