### ISSUE TITLE
如何验证该拦截是否生效

### ISSUE THREAD

**Issue by xuchang86** [pengzhile/ja-netfilter#19]
知了哥，如何验证这个拦截是否生效了，我用了最新2021.3，现在是试用用户30天，agent和配置文件都配了，不知道有没有拦截生效。开发工具上显示的是还有一个月过期。

**Comment by ddjoker** [comment]
这个拦截应该是确实生效了的  但是这个只是拦截了  其他没做啥  貌似   应该自己想办法写插件构造返回体 或者处理相关的处理类的

**Comment by CocosGames** [comment]
以前我用Tomcat做了个类似的玩意儿…看着自欺欺人的“已注册～”挺有成就感。
