### ISSUE TITLE
入正是不可能入正的，只能找些key能打开一天是一天这样子

### ISSUE THREAD

**Issue by ykk648** [pengzhile/ja-netfilter#23]

**Comment by ykk648** [comment]
pycharm 2021.3 已经完美入正，issue close

**Comment by xuchang86** [comment]
你入正后的效果是咋样的啊，我咋检验不出来入正的效果。

**Comment by ykk648** [comment]
@xuchang86 
key可以用，不会先success然后被ban
然后 eval reset 可以用，日期都可以无限更新
