### ISSUE TITLE
releases page 里面没有东西

### ISSUE THREAD

**Issue by EDOUP** [pengzhile/ja-netfilter#4]
打扰大佬了，如题

**Comment by wanghe-sudo** [comment]
pull下载自己编译就好,jdk自测11ok

**Comment by WangXin3** [comment]
> pull下载自己编译就好,jdk自测11ok

我还是玩不明白 大佬求教

**Comment by pengzhile** [comment]
别急，等我我打个包发布

**Comment by whcrow** [comment]
> 别急，等我我打个包发布

打包前：提供犯罪思路
打包后：提供犯罪工具

**Comment by pengzhile** [comment]
> > 别急，等我我打个包发布
> 
> 打包前：提供犯罪思路 打包后：提供犯罪工具

别闹，这是个正经的项目啊。

**Comment by EDOUP** [comment]
> > > 别急，等我我打个包发布
> > 
> > 
> > 打包前：提供犯罪思路 打包后：提供犯罪工具
> 
> 别闹，这是个正经的项目啊。

赞，工具已备好，开始学习新科学技术了

**Comment by a601942905git** [comment]
包还没打好么，是被抓了嘛
