### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by a616101** [pengzhile/ja-netfilter#5]
配置完 javaagent，依然跳出激活视窗
需要添加什麽步骤吗？
![image](https://user-images.githubusercontent.com/4496234/143984969-4f4e5952-8b9c-4f5d-9e97-652bf46b410b.png)

**Comment by 89632a16** [comment]
咳咳...“请不要试图结合IDE Eval Resetter一文中所说热心大佬的key来使用本项目。”
