### ISSUE TITLE
mvn clean package编译的jar包添加到idea的javaagent无法启动

### ISSUE THREAD

**Issue by jounzhang** [pengzhile/ja-netfilter#6]
如题

**Comment by lxf9501** [comment]
用deploy可以

**Comment by Carlos920** [comment]
mvn clean package 用`ja-netfilter-jar-with-dependencies.jar`这个

**Comment by lym1121** [comment]
使用方法？添加到配置不能运行

**Comment by xywf221** [comment]
只需要大喊fuck neo pang 。neo pang他就会出现

**Comment by lym1121** [comment]
WTF?



在 2021-11-30 15:19:15，"dmls" ***@***.***> 写道：

只需要大喊fuck neo pang 。neo pang他就会出现

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lym1121** [comment]
-javaagent:ja-netfilter-jar-with-dependencies.jar=janf_config.txt
配置添加，貌似这个可以？！

**Comment by pengzhile** [comment]
> -javaagent:ja-netfilter-jar-with-dependencies.jar=janf_config.txt
> 配置添加，貌似这个可以？！

janf_config.txt和jar放一起时，不需要=号来配置

**Comment by xywf221** [comment]
neo pang 果然出现了

**Comment by Carlos920** [comment]
> 

怎样才能知道是否成功？debug且使用xxx.bat运行程序后有输出url等信息

**Comment by xywf221** [comment]
加入到vm上能正常启动就算成功

**Comment by Carlos920** [comment]
> > -javaagent:ja-netfilter-jar-with-dependencies.jar=janf_config.txt
> > 配置添加，貌似这个可以？！
> 
> janf_config.txt和jar放一起时，不需要=号来配置

怎样才能知道是否成功？debug且使用xxx.bat运行程序后有输出url等信息

**Comment by lym1121** [comment]
> > -javaagent:ja-netfilter-jar-with-dependencies.jar=janf_config.txt
> > 配置添加，貌似这个可以？！
> 
> janf_config.txt和jar放一起时，不需要=号来配置

-javaagent:ja-netfilter-jar-with-dependencies.jar

**Comment by lym1121** [comment]
> > -javaagent:ja-netfilter-jar-with-dependencies.jar=janf_config.txt
> > 配置添加，貌似这个可以？！
> 
> janf_config.txt和jar放一起时，不需要=号来配置

-javaagent:\ja-netfilter-jar-with-dependencies.jar
可以启动，效果检测？

**Comment by pengzhile** [comment]
用我发布的包吧，注意看readme
